---

- name: create group
  group:
    name: "{{ kibana.group.name }}"
    state: present
    system: yes

- name: create user
  user:
    comment: "{{ kibana.user.comment }}"
    name: "{{ kibana.user.name }}"
    group: "{{ kibana.group.name }}"
    home: "{{ kibana.user.directory }}"
    create_home: yes
    system: yes
    password_lock: yes

- name: download kibana
  get_url:
    url: '{{ kibana.url }}'
    dest: /tmp/{{ kibana.filename }}.tar.gz
    checksum: "{{ kibana.checksum }}"
  become: yes
  become_method: su
  become_user: "{{ kibana.user.name }}"

- unarchive:
    src: /tmp/{{ kibana.filename }}.tar.gz
    dest: /tmp
    remote_src: yes
  become: yes
  become_method: su
  become_user: "{{ kibana.user.name }}"

- copy:
    src: /tmp/{{ kibana.filename }}/{{ item }}
    dest: "{{ kibana.user.directory }}"
    remote_src: yes
    mode: preserve
  become: yes
  become_method: su
  become_user: "{{ kibana.user.name }}"
  with_items:
    - .nodegit_binaries
    - bin
    - built_assets
    - config
    - data
    - node
    - node_modules
    - optimize
    - package.json
    - plugins
    - src
    - webpackShims
    - x-pack
  notify: restart supervisor

- file:
    path: "{{ kibana.user.directory }}/logs"
    state: directory
    owner: "{{ kibana.user.name }}"
    group: "{{ kibana.group.name }}"
    mode: 0755
    recurse: yes
- file:
    path: "{{ kibana.user.directory }}/bin"
    mode: 0755
    recurse: yes

- name: copy kibana.yml
  template:
    src: kibana.yml.j2
    dest: "{{ kibana.user.directory }}/config/kibana.yml"
    owner: "{{ kibana.user.name }}"
    group: "{{ kibana.group.name }}"
    mode: 0640
  notify: restart supervisor


- block:
    - template:
        src: security_limits.conf.j2
        dest: /etc/security/limits.d/99-kibana.conf
        owner: root
        group: root
        mode: 0644
      notify: reboot system
    - template:
        src: sysctl.conf.j2
        dest: /etc/sysctl.d/99-kibana.conf
        owner: root
        group: root
        mode: 0644
      notify: reboot system

- block:
    - replace:
        path: /etc/supervisord.conf
        regexp: ^minfds=[0-9]*
        replace: minfds=65536
      notify: restart supervisor
    - name: add kibana configuration
      template:
        src: supervisor.conf.j2
        dest: "{{ supervisor.config_directory }}/kibana.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart supervisor

- name: start kibana
  supervisorctl:
    config: "{{ supervisor.config_directory }}/kibana.conf"
    name: kibana
    state: present
